version: '3.8'

services:
  app:
    build:
      context: .
      target: ${NODE_ENV:-production}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vitrine_cogna?schema=public
    volumes:
      - .:/app
      - /app/node_modules
    command: ${COMMAND:-node src/server.js}
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vitrine_cogna
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
